SET(CPACK_PACKAGE_NAME "lab06hw")
SET(CPACK_PACKAGE_DESCRIPTION "Release SolverApp with multiplatform packages")
SET(CPACK_PACKAGE_VENDOR "BMSTU")
SET(CPACK_PACKAGE_VERSION ${PROJECT_VERSION})

include(InstallRequiredSystemLibraries)

SET(CPACK_RESOURCE_FILE_LICENSE "${CMAKE_SOURCE_DIR}/LICENSE")
SET(CPACK_GENERATORS "TGZ;ZIP;DEB;RPM;WIX;DragNDrop")
SET(CPACK_COMPONENTS_ALL "formatter_lib;formatter_ex_lib;solver_lib;hello_world_application;solver_application")

#  Source package
SET(CPACK_SOURCE_GENERATOR "TGZ")
SET(CPACK_SOURCE_IGNORE_FILES
    "/.git/;"
    "/build/;"
)

# DEB package
IF (CPACK_GENERATOR STREQUAL "DEB")
    SET(CPACK_DEBIAN_PACKAGE_MAINTAINER "CoF-Luke")
    SET(CPACK_DEBIAN_PACKAGE_SHLIBDEPS ON)
    SET(CPACK_DEBIAN_PACKAGE_DEPENDS "libc6 (>= 2.31), libstdc++6 (>= 11), libm6, libgcc-s1")
ENDIF()

# RPM package
IF (CPACK_GENERATOR STREQUAL "RPM")
    SET(CPACK_RPM_PACKAGE_REQUIRES "libc6 >= 2.31, libstdc++ >= 11, libm, libgcc")
ENDIF()

# WIX package
IF (CPACK_GENERATOR STREQUAL "WIX")
    SET(CPACK_WIX_PRODUCT_GUID "db2c0a6f-7f18-4b38-b2e2-c3ee70f51c39")
    SET(CPACK_WIX_UPGRADE_GUID "47a3fe97-e19c-4c16-8f8d-907e425e1e23")
    set(CPACK_WIX_CMAKE_PACKAGE_REGISTRY TRUE)
    set(CPACK_WIX_ARCHITECTURE "x64")
ENDIF()

# DragNDrop package
IF (CPACK_GENERATOR STREQUAL "DragNDrop")
    SET(CPACK_DMG_FORMAT UDZO)
ENDIF()