name: Create Docker, Build and Get Log

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build and get log
        run: docker build -t logger .
        

      - name: Run Docker Container and Get Log
        run: |
          docker run \
            -v ${{ github.workspace }}:/app/src:ro \
            -v ${{ github.workspace }}/build:/app/build \
            -v ${{ github.workspace }}/artifacts:/artifacts \
            logger

      - name: Upload Log Artifact
        uses: actions/upload-artifact@v4
        with:
          name: log-file
          path: artifacts/log.txt