name: Create Docker, Build and Get Log

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build and get log
        id: build_and_log
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: false
          build-args: |
            BUILD_VERSION: ${{ github.run_number }}
        
      - name: Output Image Name
        run: |
            echo "Image name: "
            echo ${{ steps.docker_build.outputs.image }}

      - name: Run Docker Container and Get Log
        run: |
          docker run \
            -v ${{ github.workspace }}:/app/src:ro \
            -v ${{ github.workspace }}/build:/app/build \
            -v ${{ github.workspace }}/artifacts:/artifacts \
            ${{ steps.build_and_log.outputs.image }}

      - name: Upload Log Artifact
        uses: actions/upload-artifact@v4
        with:
          name: log-file
          path: artifacts/log.txt